language: minimal

jobs:

  include:

    - stage: build
      os: linux
      dist: xenial
      env: GIMME_GO_VERSION=1.12.9 GIMME_OS=linux GIMME_ARCH=amd64

    -
      os: osx
      env: GIMME_GO_VERSION=1.12.9 GIMME_OS=darwin GIMME_ARCH=amd64 GOPATH=$HOME/gopath
      install:
        - HOMEBREW_NO_AUTO_UPDATE=1 brew install gimme
        - mkdir -p $GOPATH

script:
  - eval "$(gimme)"
  - go get github.com/optimizely/go-sdk
  - ln -s $TRAVIS_BUILD_DIR $GOPATH/src/github.com/optimizely/go-testapp
  - cd $GOPATH/src/github.com/optimizely/go-testapp/app && go get
  - ls -al $GOPATH/bin/app
  - if [[ `which md5` ]]; then md5 $GOPATH/bin/app; else md5sum $GOPATH/bin/app; fi
